In [1]:
import numpy as np
import pandas as pd
df =pd.read_csv("/content/job_postings.csv")

In [3]:
print("First 5 rows of the dataset")
df.head()

First 5 rows of the dataset

,job_link,last_processed_time,last_status,got_summary,got_ner,is_being_worked,job_title,company,job_location,first_seen,search_city,search_country,search_position,job_level,job_type
0,https://www.linkedin.com/jobs/view/senior-mach...,2024-01-21 08:08:48.031964+00,Finished NER,t,t,f,Senior Machine Learning Engineer,Jobs for Humanity,"New Haven, CT",2024-01-14,East Haven,United States,Agricultural-Research Engineer,Mid senior,Onsite
1,https://www.linkedin.com/jobs/view/principal-s...,2024-01-20 04:02:12.331406+00,Finished NER,t,t,f,"Principal Software Engineer, ML Accelerators",Aurora,"San Francisco, CA",2024-01-14,El Cerrito,United States,Set-Key Driver,Mid senior,Onsite
2,https://www.linkedin.com/jobs/view/senior-etl-...,2024-01-21 08:08:31.941595+00,Finished NER,t,t,f,Senior ETL Data Warehouse Specialist,Adame Services LLC,"New York, NY",2024-01-14,Middletown,United States,Technical Support Specialist,Associate,Onsite
3,https://www.linkedin.com/jobs/view/senior-data...,2024-01-20 15:30:55.796572+00,Finished NER,t,t,f,Senior Data Warehouse Developer / Architect,Morph Enterprise,"Harrisburg, PA",2024-01-12,Lebanon,United States,Architect,Mid senior,Onsite
4,https://www.linkedin.com/jobs/view/lead-data-e...,2024-01-21 08:08:58.312124+00,Finished NER,t,t,f,Lead Data Engineer,Dice,"Plano, TX",2024-01-14,McKinney,United States,Maintenance Data Analyst,Mid senior,Onsite

In [5]:
df.dropna(subset = ['job_title', 'company', 'job_location'],inplace=True)

In [6]:
df.describe()

,job_link,last_processed_time,last_status,got_summary,got_ner,is_being_worked,job_title,company,job_location,first_seen,search_city,search_country,search_position,job_level,job_type
count,12216,12216,12216,12216,12216,12216,12216,12216,12216,12216,12216,12216,12216,12216,12216
unique,12216,5762,1,1,1,1,6483,3947,2049,6,801,4,711,2,3
top,https://www.linkedin.com/jobs/view/senior-mach...,2024-01-19 09:45:09.215838+00,Finished NER,t,t,f,Senior Data Engineer,Jobs for Humanity,"New York, NY",2024-01-13,Greater London,United States,Data Entry Clerk,Mid senior,Onsite
freq,1,6455,12216,12216,12216,12216,285,732,280,4946,189,10290,1088,10918,12187

In [7]:
top_job_titles = df['job_title'].value_counts().head(5)
print("\nTop 5 Job Titles:")
print(top_job_titles)

top_companies = df['company'].value_counts().head(5)
print("\nTop 5 Companies:")
print(top_companies)


top_locations = df['job_location'].value_counts().head(5)
print("\nTop 5 Job Locations")
print(top_locations)

job_type_distribution = df['job_type'].value_counts()
print("\nJob Type Distribution")
print(job_type_distribution)

Top 5 Job Titles:
job_title
Senior Data Engineer     285
Senior Data Analyst      163
Data Engineer            149
Senior MLOps Engineer    138
Data Analyst             137
Name: count, dtype: int64

Top 5 Companies:
company
Jobs for Humanity          732
Recruiting from Scratch    390
Dice                       193
Agoda                      172
ClearanceJobs              166
Name: count, dtype: int64

Top 5 Job Locations
job_location
New York, NY                       280
Chicago, IL                        232
London, England, United Kingdom    232
San Francisco, CA                  199
Washington, DC                     173
Name: count, dtype: int64

Job Type Distribution
job_type
Onsite    12187
Remote       18
Hybrid       11
Name: count, dtype: int64